name: Build CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile LaTeX to PDF
      run: pdflatex cv.tex

    - name: Commit and Push PDF
      run: |
        git config --global user.email "niloygalib@gmail.com"
        git config --global user.name "galib079"
        git add cv.pdf
        git commit -m "Update CV"
        git push
