name: Build and Publish CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: LaTeX Action
      uses: fudan-mse/latex-action@v0.0.1
            
