name: Build CV

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-full

    - name: Compile LaTeX to PDF
      run: pdflatex cv.tex

    - name: Upload PDF as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: cv-pdf
        path: cv.pdf
