name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document with pre/post compile actions
        uses: ./
        with:
          root_file: cv.tex
          working_directory: ./
          pre_compile: |
            rm test.pdf
          post_compile: |
            ls test.pdf
