name: Publish PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up LaTeX
      run: sudo apt-get install -y texlive-full

    - name: Compile LaTeX document
      run: pdflatex cv.tex

    - name: Deploy to GitHub Pages
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "niloygalib@gmail.com"
        git config --global user.name "Md Riazul Galib Niloy"
        git checkout -b gh-pages
        git add cv.pdf
        git commit -m "Update CV"
        git push git@github.com:galib079/md-riazul-galib-cv.git gh-pages --force
