name: Deploy PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Copy
        run: |
          mkdir out
          cp ./cv.pdf ./out/cv.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: out/thesis.pdf
      - name: Run make4ht 
        uses: docker://ghcr.io/michal-h21/make4ht-action:latest 
        env: 
          command: "make4ht -u -d out cv.tex" 
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          SINGLE_COMMIT: true
          FOLDER: out
          GIT_CONFIG_NAME: galib079
          GIT_CONFIG_EMAIL: niloygalib@gmail.com
